function preload() {
    initialScreenImage = loadImage('images/backgrounds/telaInicial.png')
    initialScreenFont = loadFont('assets/fonteTelaInicial.otf')
    skyImage = loadImage('images/backgrounds/Sky.png')
    BGDecorImage = loadImage('images/backgrounds/BG_Decor.png')
    foregroundImage = loadImage('images/backgrounds/Foreground.png')
    grassImage = loadImage('images/backgrounds/Ground.png')
    //backgroundImage = loadImage('images/backgrounds/floresta.png')
    gameOverImage = loadImage('assets/game-over.png')
    lifeImage = loadImage('assets/coracao.png')
    characterImage = loadImage('images/character/correndo.png')
    enemyImage = loadImage('images/enemies/gotinha.png')
    trollImage = loadImage('images/enemies/troll.png')
    wingSlimeImage = loadImage('images/enemies/gotinha-voadora.png')
    gameSound = loadSound('songs/trilha_jogo.mp3')
    jumpSound = loadSound('songs/somPulo.mp3')
  }